
- title: Python Developer
  description: I am most experienced with Python. I've created the first version of my portfolio with Python and Flask!
  link-text: More Coming Soon

- title: Web Designer
  description: I have used HTML, CSS, JavaScript, and Bootstrap. I have recently began developing with Jekyll too!
  link-text: More Coming Soon

- title: Art and Etsy
  description: I enjoy creating artworks in my free time. This includes traditional and digital artwork. I have also created simple leather wallets!
  link-text: More Coming Soon
  link: https://www.etsy.com/shop/TachasWorkshop